-- local remap = require("karulosu.keymap")
-- local nnoremap = remap.nnoremap
--
-- nnoremap('f', ":HopWordMW<cr>")
-- nnoremap('F', ":HopPattern<cr>")
-- nnoremap('t', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })<cr>")
-- nnoremap('T', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })<cr>")
